// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/agent/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains agent registration information (new mechanism)
type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistrationKey string                 `protobuf:"bytes,1,opt,name=registration_key,json=registrationKey,proto3" json:"registration_key,omitempty"` // Registration key from pre-created agent
	OsType          string                 `protobuf:"bytes,2,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`                            // Operating system type (windows/linux/darwin) - auto-detected
	AgentVersion    string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`          // Agent version (from build-time injection)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRegistrationKey() string {
	if x != nil {
		return x.RegistrationKey
	}
	return ""
}

func (x *RegisterRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RegisterResponse contains registration result (new mechanism)
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                   // Unique agent ID assigned by server
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                      // Authentication token for subsequent requests
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`                                // Hostname from pre-created agent
	CloudProvider string                 `protobuf:"bytes,6,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"` // Cloud provider from pre-created agent
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`                                    // Region from pre-created agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterResponse) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *RegisterResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// HeartbeatRequest contains heartbeat information
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`        // Agent status (running/idle/busy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// HeartbeatResponse acknowledges heartbeat
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,3,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// StaticInfoRequest contains static system information
type StaticInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Info          *StaticInfo            `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticInfoRequest) Reset() {
	*x = StaticInfoRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticInfoRequest) ProtoMessage() {}

func (x *StaticInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticInfoRequest.ProtoReflect.Descriptor instead.
func (*StaticInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StaticInfoRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StaticInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StaticInfoRequest) GetInfo() *StaticInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// StaticInfo contains static host information
type StaticInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hostname          string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType            string                 `protobuf:"bytes,2,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`                 // windows/linux/darwin
	OsVersion         string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`        // OS version string
	Architecture      string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`                   // amd64/arm64/etc
	CpuCores          int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`          // Number of CPU cores
	CpuModel          string                 `protobuf:"bytes,6,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`           // CPU model name
	TotalMemory       int64                  `protobuf:"varint,7,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"` // Total memory in bytes
	TotalDisk         int64                  `protobuf:"varint,8,opt,name=total_disk,json=totalDisk,proto3" json:"total_disk,omitempty"`       // Total disk space in bytes
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,9,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	KernelVersion     string                 `protobuf:"bytes,10,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	BootTime          int64                  `protobuf:"varint,11,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"` // Boot time as Unix timestamp
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StaticInfo) Reset() {
	*x = StaticInfo{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticInfo) ProtoMessage() {}

func (x *StaticInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticInfo.ProtoReflect.Descriptor instead.
func (*StaticInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StaticInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *StaticInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *StaticInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *StaticInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *StaticInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *StaticInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *StaticInfo) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *StaticInfo) GetTotalDisk() int64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *StaticInfo) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *StaticInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *StaticInfo) GetBootTime() int64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

// NetworkInterface represents a network interface
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,2,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Mtu           int64                  `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetMtu() int64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// StaticInfoResponse acknowledges static info report
type StaticInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticInfoResponse) Reset() {
	*x = StaticInfoResponse{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticInfoResponse) ProtoMessage() {}

func (x *StaticInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticInfoResponse.ProtoReflect.Descriptor instead.
func (*StaticInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StaticInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StaticInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DynamicMetricsRequest contains dynamic system metrics
type DynamicMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Metrics       *DynamicMetrics        `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicMetricsRequest) Reset() {
	*x = DynamicMetricsRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMetricsRequest) ProtoMessage() {}

func (x *DynamicMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMetricsRequest.ProtoReflect.Descriptor instead.
func (*DynamicMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DynamicMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DynamicMetricsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DynamicMetricsRequest) GetMetrics() *DynamicMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// DynamicMetrics contains dynamic system metrics
type DynamicMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	CpuUsagePercent    float64                `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsed         int64                  `protobuf:"varint,3,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`                // Used memory in bytes
	MemoryAvailable    int64                  `protobuf:"varint,4,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"` // Available memory in bytes
	MemoryUsagePercent float64                `protobuf:"fixed64,5,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsage          []*DiskUsage           `protobuf:"bytes,6,rep,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetworkStats       []*NetworkStats        `protobuf:"bytes,7,rep,name=network_stats,json=networkStats,proto3" json:"network_stats,omitempty"`
	ProcessCount       int32                  `protobuf:"varint,8,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	LoadAverage_1M     float64                `protobuf:"fixed64,9,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	LoadAverage_5M     float64                `protobuf:"fixed64,10,opt,name=load_average_5m,json=loadAverage5m,proto3" json:"load_average_5m,omitempty"`
	LoadAverage_15M    float64                `protobuf:"fixed64,11,opt,name=load_average_15m,json=loadAverage15m,proto3" json:"load_average_15m,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DynamicMetrics) Reset() {
	*x = DynamicMetrics{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMetrics) ProtoMessage() {}

func (x *DynamicMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMetrics.ProtoReflect.Descriptor instead.
func (*DynamicMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DynamicMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DynamicMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *DynamicMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *DynamicMetrics) GetMemoryAvailable() int64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *DynamicMetrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *DynamicMetrics) GetDiskUsage() []*DiskUsage {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

func (x *DynamicMetrics) GetNetworkStats() []*NetworkStats {
	if x != nil {
		return x.NetworkStats
	}
	return nil
}

func (x *DynamicMetrics) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *DynamicMetrics) GetLoadAverage_1M() float64 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *DynamicMetrics) GetLoadAverage_5M() float64 {
	if x != nil {
		return x.LoadAverage_5M
	}
	return 0
}

func (x *DynamicMetrics) GetLoadAverage_15M() float64 {
	if x != nil {
		return x.LoadAverage_15M
	}
	return 0
}

// DiskUsage represents disk usage for a mount point
type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Filesystem    string                 `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`         // Total space in bytes
	Used          int64                  `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`           // Used space in bytes
	Available     int64                  `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"` // Available space in bytes
	UsagePercent  float64                `protobuf:"fixed64,6,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DiskUsage) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskUsage) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskUsage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskUsage) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskUsage) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *DiskUsage) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

// NetworkStats represents network statistics for an interface
type NetworkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	BytesSent     int64                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     int64                  `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   int64                  `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   int64                  `protobuf:"varint,5,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	ErrorsIn      int64                  `protobuf:"varint,6,opt,name=errors_in,json=errorsIn,proto3" json:"errors_in,omitempty"`
	ErrorsOut     int64                  `protobuf:"varint,7,opt,name=errors_out,json=errorsOut,proto3" json:"errors_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkStats) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkStats) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkStats) GetBytesRecv() int64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetworkStats) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkStats) GetPacketsRecv() int64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetworkStats) GetErrorsIn() int64 {
	if x != nil {
		return x.ErrorsIn
	}
	return 0
}

func (x *NetworkStats) GetErrorsOut() int64 {
	if x != nil {
		return x.ErrorsOut
	}
	return 0
}

// DynamicMetricsResponse acknowledges metrics report
type DynamicMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicMetricsResponse) Reset() {
	*x = DynamicMetricsResponse{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMetricsResponse) ProtoMessage() {}

func (x *DynamicMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMetricsResponse.ProtoReflect.Descriptor instead.
func (*DynamicMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DynamicMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DynamicMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FileChunk represents a chunk of file data
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // Relative or absolute file path
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`         // Total file size
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                                // Offset of this chunk
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                     // Chunk data
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`                             // MD5 checksum of entire file (sent in last chunk)
	IsLastChunk   bool                   `protobuf:"varint,8,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"` // Indicates last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileChunk) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileChunk) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FileChunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

// FileTransferResponse indicates file transfer result
type FileTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                       // Server-assigned file ID
	BytesReceived int64                  `protobuf:"varint,4,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"` // Total bytes received
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransferResponse) Reset() {
	*x = FileTransferResponse{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransferResponse) ProtoMessage() {}

func (x *FileTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransferResponse.ProtoReflect.Descriptor instead.
func (*FileTransferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *FileTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransferResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileTransferResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

// FileDownloadRequest requests a file download
type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // File ID to download
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FileDownloadRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FileDownloadRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FileDownloadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// CommandRequest contains command execution request
type CommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                   // Command to execute
	Args           []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Command arguments
	WorkingDir     string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory
	Env            map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // Execution timeout
	ExecutionId    string                 `protobuf:"bytes,8,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`                                        // Unique execution ID for tracking
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CommandRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// CommandMessage is used for bidirectional streaming between server and agent
type CommandMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // Message type: "command", "completion", "heartbeat"
	// For type="command": Server sends command to agent
	CommandRequest *CommandRequest `protobuf:"bytes,2,opt,name=command_request,json=commandRequest,proto3" json:"command_request,omitempty"`
	// For type="completion": Agent reports completion to server
	CommandCompletion *CommandCompletion `protobuf:"bytes,3,opt,name=command_completion,json=commandCompletion,proto3" json:"command_completion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CommandMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommandMessage) GetCommandRequest() *CommandRequest {
	if x != nil {
		return x.CommandRequest
	}
	return nil
}

func (x *CommandMessage) GetCommandCompletion() *CommandCompletion {
	if x != nil {
		return x.CommandCompletion
	}
	return nil
}

// CommandCompletion contains command execution completion report
type CommandCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`       // Execution ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // "completed" or "failed"
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`               // Process exit code
	StdoutPreview string                 `protobuf:"bytes,4,opt,name=stdout_preview,json=stdoutPreview,proto3" json:"stdout_preview,omitempty"` // stdout output (truncated to 10KB)
	StderrPreview string                 `protobuf:"bytes,5,opt,name=stderr_preview,json=stderrPreview,proto3" json:"stderr_preview,omitempty"` // stderr output (truncated to 10KB)
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`    // Error message if execution failed
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`         // Execution duration in milliseconds
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandCompletion) Reset() {
	*x = CommandCompletion{}
	mi := &file_api_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandCompletion) ProtoMessage() {}

func (x *CommandCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandCompletion.ProtoReflect.Descriptor instead.
func (*CommandCompletion) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CommandCompletion) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CommandCompletion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandCompletion) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandCompletion) GetStdoutPreview() string {
	if x != nil {
		return x.StdoutPreview
	}
	return ""
}

func (x *CommandCompletion) GetStderrPreview() string {
	if x != nil {
		return x.StderrPreview
	}
	return ""
}

func (x *CommandCompletion) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandCompletion) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CommandCompletion) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_agent_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/agent/agent.proto\x12\x05agent\"z\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\x10registration_key\x18\x01 \x01(\tR\x0fregistrationKey\x12\x17\n" +
	"\aos_type\x18\x02 \x01(\tR\x06osType\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\"\xd2\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12%\n" +
	"\x0ecloud_provider\x18\x06 \x01(\tR\rcloudProvider\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\"y\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"r\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10server_timestamp\x18\x03 \x01(\x03R\x0fserverTimestamp\"k\n" +
	"\x11StaticInfoRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12%\n" +
	"\x04info\x18\x03 \x01(\v2\x11.agent.StaticInfoR\x04info\"\x8c\x03\n" +
	"\n" +
	"StaticInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x02 \x01(\tR\x06osType\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tcpu_model\x18\x06 \x01(\tR\bcpuModel\x12!\n" +
	"\ftotal_memory\x18\a \x01(\x03R\vtotalMemory\x12\x1d\n" +
	"\n" +
	"total_disk\x18\b \x01(\x03R\ttotalDisk\x12F\n" +
	"\x12network_interfaces\x18\t \x03(\v2\x17.agent.NetworkInterfaceR\x11networkInterfaces\x12%\n" +
	"\x0ekernel_version\x18\n" +
	" \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\tboot_time\x18\v \x01(\x03R\bbootTime\"|\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fip_addresses\x18\x02 \x03(\tR\vipAddresses\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x03R\x03mtu\"H\n" +
	"\x12StaticInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x15DynamicMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12/\n" +
	"\ametrics\x18\x03 \x01(\v2\x15.agent.DynamicMetricsR\ametrics\"\xe2\x03\n" +
	"\x0eDynamicMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12\x1f\n" +
	"\vmemory_used\x18\x03 \x01(\x03R\n" +
	"memoryUsed\x12)\n" +
	"\x10memory_available\x18\x04 \x01(\x03R\x0fmemoryAvailable\x120\n" +
	"\x14memory_usage_percent\x18\x05 \x01(\x01R\x12memoryUsagePercent\x12/\n" +
	"\n" +
	"disk_usage\x18\x06 \x03(\v2\x10.agent.DiskUsageR\tdiskUsage\x128\n" +
	"\rnetwork_stats\x18\a \x03(\v2\x13.agent.NetworkStatsR\fnetworkStats\x12#\n" +
	"\rprocess_count\x18\b \x01(\x05R\fprocessCount\x12&\n" +
	"\x0fload_average_1m\x18\t \x01(\x01R\rloadAverage1m\x12&\n" +
	"\x0fload_average_5m\x18\n" +
	" \x01(\x01R\rloadAverage5m\x12(\n" +
	"\x10load_average_15m\x18\v \x01(\x01R\x0eloadAverage15m\"\xb9\x01\n" +
	"\tDiskUsage\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x03R\x04used\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x03R\tavailable\x12#\n" +
	"\rusage_percent\x18\x06 \x01(\x01R\fusagePercent\"\xf5\x01\n" +
	"\fNetworkStats\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x03 \x01(\x03R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x03R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\x05 \x01(\x03R\vpacketsRecv\x12\x1b\n" +
	"\terrors_in\x18\x06 \x01(\x03R\berrorsIn\x12\x1d\n" +
	"\n" +
	"errors_out\x18\a \x01(\x03R\terrorsOut\"L\n" +
	"\x16DynamicMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe4\x01\n" +
	"\tFileChunk\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\"\n" +
	"\ris_last_chunk\x18\b \x01(\bR\visLastChunk\"\x8a\x01\n" +
	"\x14FileTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12%\n" +
	"\x0ebytes_received\x18\x04 \x01(\x03R\rbytesReceived\"_\n" +
	"\x13FileDownloadRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\"\xc6\x02\n" +
	"\x0eCommandRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x120\n" +
	"\x03env\x18\x06 \x03(\v2\x1e.agent.CommandRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12!\n" +
	"\fexecution_id\x18\b \x01(\tR\vexecutionId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x0eCommandMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12>\n" +
	"\x0fcommand_request\x18\x02 \x01(\v2\x15.agent.CommandRequestR\x0ecommandRequest\x12G\n" +
	"\x12command_completion\x18\x03 \x01(\v2\x18.agent.CommandCompletionR\x11commandCompletion\"\x9d\x02\n" +
	"\x11CommandCompletion\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12%\n" +
	"\x0estdout_preview\x18\x04 \x01(\tR\rstdoutPreview\x12%\n" +
	"\x0estderr_preview\x18\x05 \x01(\tR\rstderrPreview\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp2\xec\x03\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponse\x12G\n" +
	"\x10ReportStaticInfo\x12\x18.agent.StaticInfoRequest\x1a\x19.agent.StaticInfoResponse\x12S\n" +
	"\x14ReportDynamicMetrics\x12\x1c.agent.DynamicMetricsRequest\x1a\x1d.agent.DynamicMetricsResponse\x12=\n" +
	"\n" +
	"UploadFile\x12\x10.agent.FileChunk\x1a\x1b.agent.FileTransferResponse(\x01\x12>\n" +
	"\fDownloadFile\x12\x1a.agent.FileDownloadRequest\x1a\x10.agent.FileChunk0\x01\x12B\n" +
	"\x0eExecuteCommand\x12\x15.agent.CommandMessage\x1a\x15.agent.CommandMessage(\x010\x01B8Z6repo.yetoa.com/yetoa/xuannexus/api/proto/agent;agentpbb\x06proto3"

var (
	file_api_proto_agent_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_agent_proto_rawDescData []byte
)

func file_api_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_agent_proto_rawDesc), len(file_api_proto_agent_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_agent_proto_rawDescData
}

var file_api_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_agent_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: agent.RegisterRequest
	(*RegisterResponse)(nil),       // 1: agent.RegisterResponse
	(*HeartbeatRequest)(nil),       // 2: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: agent.HeartbeatResponse
	(*StaticInfoRequest)(nil),      // 4: agent.StaticInfoRequest
	(*StaticInfo)(nil),             // 5: agent.StaticInfo
	(*NetworkInterface)(nil),       // 6: agent.NetworkInterface
	(*StaticInfoResponse)(nil),     // 7: agent.StaticInfoResponse
	(*DynamicMetricsRequest)(nil),  // 8: agent.DynamicMetricsRequest
	(*DynamicMetrics)(nil),         // 9: agent.DynamicMetrics
	(*DiskUsage)(nil),              // 10: agent.DiskUsage
	(*NetworkStats)(nil),           // 11: agent.NetworkStats
	(*DynamicMetricsResponse)(nil), // 12: agent.DynamicMetricsResponse
	(*FileChunk)(nil),              // 13: agent.FileChunk
	(*FileTransferResponse)(nil),   // 14: agent.FileTransferResponse
	(*FileDownloadRequest)(nil),    // 15: agent.FileDownloadRequest
	(*CommandRequest)(nil),         // 16: agent.CommandRequest
	(*CommandMessage)(nil),         // 17: agent.CommandMessage
	(*CommandCompletion)(nil),      // 18: agent.CommandCompletion
	nil,                            // 19: agent.CommandRequest.EnvEntry
}
var file_api_proto_agent_agent_proto_depIdxs = []int32{
	5,  // 0: agent.StaticInfoRequest.info:type_name -> agent.StaticInfo
	6,  // 1: agent.StaticInfo.network_interfaces:type_name -> agent.NetworkInterface
	9,  // 2: agent.DynamicMetricsRequest.metrics:type_name -> agent.DynamicMetrics
	10, // 3: agent.DynamicMetrics.disk_usage:type_name -> agent.DiskUsage
	11, // 4: agent.DynamicMetrics.network_stats:type_name -> agent.NetworkStats
	19, // 5: agent.CommandRequest.env:type_name -> agent.CommandRequest.EnvEntry
	16, // 6: agent.CommandMessage.command_request:type_name -> agent.CommandRequest
	18, // 7: agent.CommandMessage.command_completion:type_name -> agent.CommandCompletion
	0,  // 8: agent.AgentService.Register:input_type -> agent.RegisterRequest
	2,  // 9: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	4,  // 10: agent.AgentService.ReportStaticInfo:input_type -> agent.StaticInfoRequest
	8,  // 11: agent.AgentService.ReportDynamicMetrics:input_type -> agent.DynamicMetricsRequest
	13, // 12: agent.AgentService.UploadFile:input_type -> agent.FileChunk
	15, // 13: agent.AgentService.DownloadFile:input_type -> agent.FileDownloadRequest
	17, // 14: agent.AgentService.ExecuteCommand:input_type -> agent.CommandMessage
	1,  // 15: agent.AgentService.Register:output_type -> agent.RegisterResponse
	3,  // 16: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	7,  // 17: agent.AgentService.ReportStaticInfo:output_type -> agent.StaticInfoResponse
	12, // 18: agent.AgentService.ReportDynamicMetrics:output_type -> agent.DynamicMetricsResponse
	14, // 19: agent.AgentService.UploadFile:output_type -> agent.FileTransferResponse
	13, // 20: agent.AgentService.DownloadFile:output_type -> agent.FileChunk
	17, // 21: agent.AgentService.ExecuteCommand:output_type -> agent.CommandMessage
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_agent_agent_proto_init() }
func file_api_proto_agent_agent_proto_init() {
	if File_api_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_agent_proto_rawDesc), len(file_api_proto_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_agent_proto = out.File
	file_api_proto_agent_agent_proto_goTypes = nil
	file_api_proto_agent_agent_proto_depIdxs = nil
}
